### ISSUE TITLE
Fail on the '-t' key

### ISSUE THREAD

**Issue by einse** [einse/trigger#3]
The output is following:
```
Traceback (most recent call last):
  File "trigger.py", line 104, in <module>
    output(j, token)
  File "/home/helio/Загрузки/trigger-1.1.1/output.py", line 14, in output
    with codecs.open(filename, """a""", encoding="utf-8") as f:
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 21] Is a directory: u'.'
```

**Comment by einse** [comment]
https://github.com/einse/trigger/commit/3e049b3b7d1c61591619838e0d4294078498b52f
